### PR TITLE
Set env var when parsing from `robot-descriptions`

### PR DESCRIPTION
**Pull request by flferretti**
Requires https://github.com/flferretti/resolve-robotics-uri-cpp/tree/feature/custom_path. PR will be open, see https://github.com/ami-iit/resolve-robotics-uri-py/issues/12

### CODE REVIEW

**Comment by lorycontixd** [comment]
@flferretti This is ready for merge?

**Comment by flferretti** [comment]
Yes. I also don't like the hardcoding, but since this problem happens only during tests using `robot-descriptions`, we can ignore it

**Comment by flferretti** [comment]
Yes, now is ready for merge. In the latest commit I avoided hardcoding the search path

**Comment by lorycontixd** [comment]
Thank you @flferretti

**Pull request merged**
